const COPY = {
  zh: {
    languageToggle: "English",
    fileInputLabel: "选择本地 AgentFlow Studio 验收文件",
    overallLabel: "交付状态",
    emptyInventory: "这里是 Contract Inspector。选择本地 artifact 后，会显示文件名、合同类型、schema_version 和解析状态。",
    emptyInspector: "选择 quality、review 或 delivery readiness artifact 后，这里会显示审查项、建议和门禁结果。",
    emptyEvidenceMap: "选择 run_manifest、package manifest 或上游证据后，这里会显示本地证据链关系。",
    emptyRiskLedger: "当前没有聚合到风险。选择文件后，会按风险来源显示 warnings、failures 和解析问题。",
    emptyAssetLedger: "选择 package 或媒体 manifest 后，这里会集中核对 final video、clips、subtitle、cover、BGM 等资产路径。",
    emptyVideo: "只预览你主动选择的 mp4 / webm / mov 文件，不跟随 manifest 路径。",
    emptyReport: "Markdown 报告会以安全文本方式展示。请选择 package_report.md 或 delivery_readiness.md。",
    notLoaded: "未加载",
    summaryIncluded: "参与验收",
    summaryExcluded: "不参与验收",
    assetsTitle: "交付包资产",
    loadNotesTitle: "加载提示",
    noDetails: "未找到详细检查项。",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    movCompatibility: "MOV 在不同浏览器中可能不可播放。",
    videoPlaybackError: "当前浏览器无法播放：",
    videoSelected: (fileName) => `正在预览本地文件：${fileName}`,
    feedbackNoArtifact: "不关联具体文件",
    feedbackCopied: "feedback_event JSON 已复制。",
    feedbackCopyFallback: "已生成 JSON；请从文本框手动复制。",
    staticText: {
      brandKicker: "内容生产验收",
      brandName: "AgentFlow Studio 本地验收台",
      importButton: "选择验收文件",
      boundaryUpload: "不上传",
      boundaryBackend: "不执行后端",
      boundaryPersistence: "不持久化",
      boundaryScanning: "不扫描目录",
      boundaryManifest: "不自动读取 manifest 路径",
      workflowKicker: "Review Flow",
      workflowTitle: "验收路径",
      navOverview: "交付总览",
      navVideo: "视频预览",
      navAssets: "资产核对",
      navRisks: "风险处理",
      navReports: "报告审阅",
      navContract: "合同检查",
      recommendedTitle: "推荐文件组",
      packageGroupTitle: "交付包",
      evidenceGroupTitle: "上游证据",
      handoffGroupTitle: "交付门禁",
      stageKicker: "Local Review Workbench",
      stageTitle: "先看成品能否交付，再看证据和风险。",
      stageSubtitle: "这里不会启动工作流。请先用 CLI 产出 AgentFlow Studio artifacts，再把需要审查的 JSON、Markdown 和视频文件选入本页。",
      statArtifactsLabel: "已选文件",
      statKnownLabel: "参与验收",
      statWarningsLabel: "风险提示",
      statErrorsLabel: "解析错误",
      summaryTitle: "交付总览",
      summaryChip: "acceptance",
      localChip: "local files",
      inspectorTitle: "审查 Inspector",
      checksChip: "checks",
      evidenceMapTitle: "证据链",
      lineageChip: "lineage",
      riskLedgerTitle: "风险处理",
      riskChip: "risk",
      assetLedgerTitle: "资产核对",
      assetChip: "assets",
      videoPreviewTitle: "视频预览",
      videoChip: "explicit file only",
      reportTitle: "报告审阅",
      escapedChip: "escaped text",
      contractInspectorTitle: "Contract Inspector",
      feedbackKicker: "M2 local copy",
      feedbackTitle: "反馈事件复制",
      feedbackChip: "copy JSON",
      feedbackBody: "生成 feedback_event JSON 并复制，不写本地文件、不上传。",
      feedbackArtifactLabel: "关联 artifact",
      feedbackDecisionLabel: "验收结论",
      feedbackRiskLabel: "风险分类",
      feedbackTimeLabel: "视频时间点（秒，可选）",
      feedbackNoteLabel: "审查备注",
      feedbackCopyButton: "生成并复制 JSON",
      feedbackFallbackHint: "Clipboard 不可用时，可以从文本框手动复制。",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "请选择 run_manifest.json",
      package: "请选择 package manifest",
      review: "请选择 review_report.json",
      readiness: "请选择 delivery_readiness.json",
    },
    summaryCards: {
      run: "运行证据",
      package: "交付包",
      review: "审查结论",
      delivery: "交付门禁",
    },
    statusLabels: {
      pass: "通过 pass",
      warning: "警告 warning",
      fail: "失败 fail",
      missing: "缺失 missing",
      unknown: "未知 unknown",
    },
    countUnit: "项",
  },
  en: {
    languageToggle: "中文",
    fileInputLabel: "Select local AgentFlow Studio review files",
    overallLabel: "Delivery status",
    emptyInventory: "This is the Contract Inspector. Select artifacts to inspect file names, contract types, schema_version, and parse status.",
    emptyInspector: "Select quality, review, or delivery readiness artifacts to inspect checks, recommendations, and gates.",
    emptyEvidenceMap: "Select run_manifest, package manifest, or upstream evidence to inspect local lineage relationships.",
    emptyRiskLedger: "No aggregated risk yet. Warnings, failures, and parse issues appear after files are selected.",
    emptyAssetLedger: "Select package or media manifests to check final video, clips, subtitles, cover, and BGM asset paths.",
    emptyVideo: "Only explicitly selected mp4 / webm / mov files are previewed. Manifest paths are not followed.",
    emptyReport: "Markdown reports are displayed as safe text. Select package_report.md or delivery_readiness.md.",
    notLoaded: "not loaded",
    summaryIncluded: "included",
    summaryExcluded: "not included",
    assetsTitle: "Package Assets",
    loadNotesTitle: "Load Notes",
    noDetails: "No detailed checks found.",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    movCompatibility: "MOV playback support varies by browser.",
    videoPlaybackError: "This browser cannot play:",
    videoSelected: (fileName) => `Previewing local file: ${fileName}`,
    feedbackNoArtifact: "No specific file",
    feedbackCopied: "feedback_event JSON copied.",
    feedbackCopyFallback: "JSON generated; copy it from the text box.",
    staticText: {
      brandKicker: "Content review",
      brandName: "AgentFlow Studio Review Desk",
      importButton: "Select review files",
      boundaryUpload: "No upload",
      boundaryBackend: "No backend execution",
      boundaryPersistence: "No persistence",
      boundaryScanning: "No directory scanning",
      boundaryManifest: "No manifest path auto-read",
      workflowKicker: "Review Flow",
      workflowTitle: "Review Path",
      navOverview: "Delivery Overview",
      navVideo: "Video Preview",
      navAssets: "Asset Check",
      navRisks: "Risk Handling",
      navReports: "Report Review",
      navContract: "Contract Check",
      recommendedTitle: "Recommended File Sets",
      packageGroupTitle: "Package run",
      evidenceGroupTitle: "Upstream evidence",
      handoffGroupTitle: "Handoff gate",
      stageKicker: "Local Review Workbench",
      stageTitle: "Judge deliverability first, then inspect evidence and risk.",
      stageSubtitle: "This page does not start workflows. Generate AgentFlow Studio artifacts with the CLI first, then select the JSON, Markdown, and video files to review.",
      statArtifactsLabel: "Selected files",
      statKnownLabel: "Acceptance inputs",
      statWarningsLabel: "Risk notes",
      statErrorsLabel: "Parse errors",
      summaryTitle: "Delivery Overview",
      summaryChip: "acceptance",
      localChip: "local files",
      inspectorTitle: "Review Inspector",
      checksChip: "checks",
      evidenceMapTitle: "Evidence Chain",
      lineageChip: "lineage",
      riskLedgerTitle: "Risk Handling",
      riskChip: "risk",
      assetLedgerTitle: "Asset Check",
      assetChip: "assets",
      videoPreviewTitle: "Video Preview",
      videoChip: "explicit file only",
      reportTitle: "Report Review",
      escapedChip: "escaped text",
      contractInspectorTitle: "Contract Inspector",
      feedbackKicker: "M2 local copy",
      feedbackTitle: "Feedback Event Copy",
      feedbackChip: "copy JSON",
      feedbackBody: "Generate and copy a feedback_event JSON object. No file writing or upload.",
      feedbackArtifactLabel: "Artifact",
      feedbackDecisionLabel: "Decision",
      feedbackRiskLabel: "Risk category",
      feedbackTimeLabel: "Video timestamp seconds",
      feedbackNoteLabel: "Reviewer note",
      feedbackCopyButton: "Generate and copy JSON",
      feedbackFallbackHint: "If Clipboard is unavailable, copy from the text box.",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "Select run_manifest.json",
      package: "Select package manifest",
      review: "Select review_report.json",
      readiness: "Select delivery_readiness.json",
    },
    summaryCards: {
      run: "Run Evidence",
      package: "Package",
      review: "Review Decision",
      delivery: "Delivery Gate",
    },
    statusLabels: {
      pass: "pass",
      warning: "warning",
      fail: "fail",
      missing: "missing",
      unknown: "unknown",
    },
    countUnit: "",
  },
};

export function getCopy(language) {
  return COPY[language] || COPY.zh;
}
