const COPY = {
  zh: {
    languageToggle: "English",
    fileInputLabel: "选择本地 NarratoCut artifacts",
    overallLabel: "总览状态",
    emptyInventory: "选择本地 artifact 后，这里会显示文件名、合同类型、schema_version 和解析状态。",
    emptyInspector: "选择 quality、review 或 delivery readiness artifact 后，这里会显示检查项和风险。",
    emptyEvidenceMap: "选择 run_manifest 或其他已知 artifact 后，这里会显示本地证据关系。",
    emptyRiskLedger: "当前没有聚合到风险。未知 JSON unknown_json 和缺失推荐 artifact 会在选择文件后出现。",
    emptyAssetLedger: "选择 package 或媒体 manifest 后，这里会集中展示 final video、clips、subtitle、cover、BGM 等资产路径。",
    emptyVideo: "只预览你主动选择的 mp4 / webm / mov 文件，不跟随 manifest 路径。",
    emptyReport: "Markdown 报告会以安全文本方式展示。请选择 package_report.md 或 delivery_readiness.md。",
    notLoaded: "未加载",
    summaryIncluded: "参与验收",
    summaryExcluded: "不参与验收",
    assetsTitle: "交付包资产",
    loadNotesTitle: "加载提示",
    noDetails: "未找到详细检查项。",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    movCompatibility: "MOV 在不同浏览器中可能不可播放。",
    videoPlaybackError: "当前浏览器无法播放：",
    videoSelected: (fileName) => `正在预览本地文件：${fileName}`,
    feedbackNoArtifact: "不关联具体文件",
    feedbackCopied: "feedback_event JSON 已复制。",
    feedbackCopyFallback: "已生成 JSON；请从文本框手动复制。",
    staticText: {
      brandKicker: "本地只读验收台",
      brandName: "NarratoCut Viewer",
      dropTitle: "选择本地 artifacts",
      dropHint: "支持 JSON / Markdown / 视频，多选后仅在浏览器内解析",
      inventoryTitle: "Artifact 清单",
      boundaryTitle: "边界",
      boundaryUpload: "不上传",
      boundaryBackend: "不执行后端",
      boundaryPersistence: "不持久化",
      boundaryScanning: "不扫描目录",
      heroKicker: "Local Acceptance Workbench",
      heroTitle: "把 NarratoCut 的运行证据、交付资产和审查风险收进一个本地验收工作台。",
      heroSubtitle: "本页面只读取你主动选择的本地文件；视频也只播放手选文件，不跟随 manifest 路径，不调用 CLI/API。",
      statArtifactsLabel: "已选文件",
      statKnownLabel: "参与验收",
      statWarningsLabel: "风险提示",
      statErrorsLabel: "解析错误",
      summaryTitle: "运行与交付包摘要",
      localChip: "local files",
      inspectorTitle: "质量与审查检查",
      checksChip: "checks",
      evidenceMapTitle: "证据关系图",
      lineageChip: "lineage",
      riskLedgerTitle: "风险台账",
      riskChip: "risk",
      assetLedgerTitle: "资产台账",
      assetChip: "assets",
      videoPreviewTitle: "本地视频预览",
      videoChip: "explicit file only",
      reportTitle: "报告预览",
      escapedChip: "escaped text",
      feedbackKicker: "M2 local copy",
      feedbackTitle: "反馈事件复制",
      feedbackChip: "copy JSON",
      feedbackBody: "生成 feedback_event JSON 并复制，不写本地文件、不上传。",
      feedbackArtifactLabel: "关联 artifact",
      feedbackDecisionLabel: "验收结论",
      feedbackRiskLabel: "风险分类",
      feedbackTimeLabel: "视频时间点（秒，可选）",
      feedbackNoteLabel: "审查备注",
      feedbackCopyButton: "生成并复制 JSON",
      feedbackFallbackHint: "Clipboard 不可用时，可从文本框手动复制。",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "请选择 run_manifest.json",
      package: "请选择 package manifest",
      review: "请选择 review_report.json",
      readiness: "请选择 delivery_readiness.json",
    },
    summaryCards: {
      run: "运行",
      package: "交付包",
      review: "审查",
      delivery: "交付门禁",
    },
    statusLabels: {
      pass: "通过 pass",
      warning: "警告 warning",
      fail: "失败 fail",
      missing: "缺失 missing",
      unknown: "未知 unknown",
    },
    countUnit: "项",
  },
  en: {
    languageToggle: "中文",
    fileInputLabel: "Select local NarratoCut artifacts",
    overallLabel: "Overall",
    emptyInventory: "Select local artifacts to inspect file names, contract types, schema_version, and parse status.",
    emptyInspector: "Select quality, review, or delivery readiness artifacts to inspect checks and risks.",
    emptyEvidenceMap: "Select run_manifest or other known artifacts to inspect local evidence relationships.",
    emptyRiskLedger: "No aggregated risk yet. unknown_json and missing recommended artifacts appear after files are selected.",
    emptyAssetLedger: "Select package or media manifests to inspect final video, clips, subtitles, cover, and BGM asset paths.",
    emptyVideo: "Only explicitly selected mp4 / webm / mov files are previewed. Manifest paths are not followed.",
    emptyReport: "Markdown reports are displayed as safe text. Select package_report.md or delivery_readiness.md.",
    notLoaded: "not loaded",
    summaryIncluded: "included",
    summaryExcluded: "not included",
    assetsTitle: "Package Assets",
    loadNotesTitle: "Load Notes",
    noDetails: "No detailed checks found.",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    movCompatibility: "MOV playback support varies by browser.",
    videoPlaybackError: "This browser cannot play:",
    videoSelected: (fileName) => `Previewing local file: ${fileName}`,
    feedbackNoArtifact: "No specific file",
    feedbackCopied: "feedback_event JSON copied.",
    feedbackCopyFallback: "JSON generated; copy it from the text box.",
    staticText: {
      brandKicker: "Local read-only workbench",
      brandName: "NarratoCut Viewer",
      dropTitle: "Select local artifacts",
      dropHint: "JSON, Markdown, and video files; parsed in this browser",
      inventoryTitle: "Artifact Inventory",
      boundaryTitle: "Boundary",
      boundaryUpload: "No upload",
      boundaryBackend: "No backend execution",
      boundaryPersistence: "No persistence",
      boundaryScanning: "No directory scanning",
      heroKicker: "Local Acceptance Workbench",
      heroTitle: "Inspect NarratoCut run evidence, delivery assets, and review risk in a local workbench.",
      heroSubtitle: "This page only reads selected files. Video preview also requires selected files and never follows manifest paths or calls CLI/API.",
      statArtifactsLabel: "Selected files",
      statKnownLabel: "Acceptance inputs",
      statWarningsLabel: "Risk notes",
      statErrorsLabel: "Parse errors",
      summaryTitle: "Run / Package Summary",
      localChip: "local files",
      inspectorTitle: "Quality / Review Inspector",
      checksChip: "checks",
      evidenceMapTitle: "Evidence Map",
      lineageChip: "lineage",
      riskLedgerTitle: "Risk Ledger",
      riskChip: "risk",
      assetLedgerTitle: "Asset Ledger",
      assetChip: "assets",
      videoPreviewTitle: "Local Video Preview",
      videoChip: "explicit file only",
      reportTitle: "Report Preview",
      escapedChip: "escaped text",
      feedbackKicker: "M2 local copy",
      feedbackTitle: "Feedback Event Copy",
      feedbackChip: "copy JSON",
      feedbackBody: "Generate and copy a feedback_event JSON object. No file writing or upload.",
      feedbackArtifactLabel: "Artifact",
      feedbackDecisionLabel: "Decision",
      feedbackRiskLabel: "Risk category",
      feedbackTimeLabel: "Video timestamp seconds",
      feedbackNoteLabel: "Reviewer note",
      feedbackCopyButton: "Generate and copy JSON",
      feedbackFallbackHint: "If Clipboard is unavailable, copy from the text box.",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "Select run_manifest.json",
      package: "Select package manifest",
      review: "Select review_report.json",
      readiness: "Select delivery_readiness.json",
    },
    summaryCards: {
      run: "Run",
      package: "Package",
      review: "Review",
      delivery: "Delivery",
    },
    statusLabels: {
      pass: "pass",
      warning: "warning",
      fail: "fail",
      missing: "missing",
      unknown: "unknown",
    },
    countUnit: "",
  },
};

export function getCopy(language) {
  return COPY[language] || COPY.zh;
}
