const COPY = {
  zh: {
    languageToggle: "English",
    fileInputLabel: "选择本地 NarratoCut artifacts",
    overallLabel: "总览状态",
    emptyInventory: "选择本地 artifact 后，这里会显示文件名、合同类型、schema_version 和解析状态。",
    emptyInspector: "选择 quality、review 或 delivery readiness artifact 后，这里会显示检查项和风险。",
    emptyReport: "Markdown 报告会以安全文本方式展示。请选择 package_report.md 或 delivery_readiness.md。",
    notLoaded: "未加载",
    summaryIncluded: "参与 summary",
    summaryExcluded: "不参与 summary",
    assetsTitle: "资产清单",
    loadNotesTitle: "加载提示",
    noDetails: "未找到详细检查项。",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    staticText: {
      brandKicker: "本地只读验收台",
      brandName: "NarratoCut Viewer",
      dropTitle: "选择本地 artifacts",
      dropHint: "支持 JSON / Markdown，多选后仅在浏览器内解析",
      inventoryTitle: "Artifact Inventory",
      boundaryTitle: "边界",
      boundaryUpload: "不上传",
      boundaryBackend: "不执行后端",
      boundaryPersistence: "不持久化",
      boundaryScanning: "不扫描目录",
      heroKicker: "Artifact Contract Inspector",
      heroTitle: "把 NarratoCut 的运行结果、交付包、审查报告和可交付风险看清楚。",
      heroSubtitle: "本页面只读取你主动选择的本地文件，不跟随 manifest 路径，不调用 CLI/API，也不保存任何状态。",
      statArtifactsLabel: "已选文件",
      statKnownLabel: "已识别合同",
      statWarningsLabel: "警告",
      statErrorsLabel: "错误",
      summaryTitle: "Run / Package Summary",
      localChip: "local files",
      inspectorTitle: "Quality / Review Inspector",
      checksChip: "checks",
      reportTitle: "Report Preview",
      escapedChip: "escaped text",
      feedbackKicker: "M2 candidate",
      feedbackTitle: "Feedback",
      feedbackBody: "当前静态切片保持只读。反馈事件复制或导出会在后续合同确认后单独实现。",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "请选择 run_manifest.json",
      package: "请选择 package manifest",
      review: "请选择 review_report.json",
      readiness: "请选择 delivery_readiness.json",
    },
    summaryCards: {
      run: "运行",
      package: "交付包",
      review: "审查",
      delivery: "交付门禁",
    },
    statusLabels: {
      pass: "通过 pass",
      warning: "警告 warning",
      fail: "失败 fail",
      missing: "缺失 missing",
      unknown: "未知 unknown",
    },
    countUnit: "项",
  },
  en: {
    languageToggle: "中文",
    fileInputLabel: "Select local NarratoCut artifacts",
    overallLabel: "Overall",
    emptyInventory: "Select local artifacts to inspect file names, contract types, schema_version, and parse status.",
    emptyInspector: "Select quality, review, or delivery readiness artifacts to inspect checks and risks.",
    emptyReport: "Markdown reports are displayed as safe text. Select package_report.md or delivery_readiness.md.",
    notLoaded: "not loaded",
    summaryIncluded: "included",
    summaryExcluded: "not included",
    assetsTitle: "Assets",
    loadNotesTitle: "Load Notes",
    noDetails: "No detailed checks found.",
    qualityTitle: "Quality Report",
    reviewTitle: "Review Report",
    readinessTitle: "Delivery Readiness",
    staticText: {
      brandKicker: "Local read-only workbench",
      brandName: "NarratoCut Viewer",
      dropTitle: "Select local artifacts",
      dropHint: "JSON and Markdown files only; parsed in this browser",
      inventoryTitle: "Artifact Inventory",
      boundaryTitle: "Boundary",
      boundaryUpload: "No upload",
      boundaryBackend: "No backend execution",
      boundaryPersistence: "No persistence",
      boundaryScanning: "No directory scanning",
      heroKicker: "Artifact Contract Inspector",
      heroTitle: "Read NarratoCut run evidence, packages, review reports, and delivery risk in one workbench.",
      heroSubtitle: "This page only reads files you select. It does not follow manifest paths, call CLI/API, or save state.",
      statArtifactsLabel: "Selected files",
      statKnownLabel: "Known contracts",
      statWarningsLabel: "Warnings",
      statErrorsLabel: "Errors",
      summaryTitle: "Run / Package Summary",
      localChip: "local files",
      inspectorTitle: "Quality / Review Inspector",
      checksChip: "checks",
      reportTitle: "Report Preview",
      escapedChip: "escaped text",
      feedbackKicker: "M2 candidate",
      feedbackTitle: "Feedback",
      feedbackBody: "This static slice remains read-only. Feedback event copy/export belongs to a later contract-backed slice.",
    },
    labels: {
      type: "type",
      class: "class",
      schema: "schema",
      role: "role",
      summary: "summary",
      warning: "warning",
      error: "error",
      recommendation: "recommendation",
      failures: "failures",
      warnings: "warnings",
      runs: "runs",
      failed: "failed",
    },
    prompts: {
      run: "Select run_manifest.json",
      package: "Select package manifest",
      review: "Select review_report.json",
      readiness: "Select delivery_readiness.json",
    },
    summaryCards: {
      run: "Run",
      package: "Package",
      review: "Review",
      delivery: "Delivery",
    },
    statusLabels: {
      pass: "pass",
      warning: "warning",
      fail: "fail",
      missing: "missing",
      unknown: "unknown",
    },
    countUnit: "",
  },
};

export function getCopy(language) {
  return COPY[language] || COPY.zh;
}
