import { DEFAULT_RUNTIME_BASE_URL } from "./runtime-client.js";


export const state = {
  baseUrl: DEFAULT_RUNTIME_BASE_URL,
  projectId: "proj_runtime_demo",
  projectGoal: "构建一个受 Provider 闸门保护的内容制作与项目记忆工作台。",
  projectType: "short_video_campaign",
  importManifestJson: "",
  sourceAssetId: "brief-main",
  sourceAssetType: "brief",
  sourceAssetLabel: "主需求摘要",
  sourceAssetSummary: "用于运行规划的短内容项目需求摘要。",
  sceneCardId: "scene-001",
  sceneCardType: "scene",
  sceneTitle: "开场镜头",
  sceneSummary: "用简洁开场镜头呈现产品核心时刻。",
  sceneTargetPlatform: "short_video",
  reviewDecision: "keep",
  reviewDecisionNote: "保留这个方向，用于下一轮复用。",
  inspectorPrompt: "干净影棚里的产品开场镜头。",
  inspectorReferenceSummary: "使用已确认的需求摘要和主要产品参考。",
  inspectorStyleDirection: "克制、精致的商业影像风格。",
  inspectorRetryIntent: "如果表现偏弱，先调整构图，再进入真实模型试跑。",
  assetProfileSeed: "examples/agentflow/production_memory_asset_profile_seed.example.json",
  promotionDecision: "promoted",
  promotionRationale: "工作台确定性链路通过；这不是长期记忆晋升。",
  feedbackNote: "保留可复用的风格档案信号，并准备下一轮。",
  health: null,
  capabilities: null,
  projects: [],
  workbench: null,
  activeView: "Projects",
  selectedCardId: "",
  selectedVariantId: "",
  selectedArtifactId: "",
  artifact: null,
  lastResult: null,
  latestAssetTestJobId: "",
  loading: false,
  error: "",
};
