import { DEFAULT_RUNTIME_BASE_URL } from "./runtime-client.js";


export const state = {
  baseUrl: DEFAULT_RUNTIME_BASE_URL,
  projectId: "proj_runtime_demo",
  projectGoal: "Build a provider-gated content memory workbench.",
  projectType: "short_video_campaign",
  importManifestJson: "",
  sourceAssetId: "brief-main",
  sourceAssetType: "brief",
  sourceAssetLabel: "Main brief",
  sourceAssetSummary: "Short campaign brief summary for runtime planning.",
  sceneCardId: "scene-001",
  sceneCardType: "scene",
  sceneTitle: "Opening scene",
  sceneSummary: "A concise opening scene describing the product moment.",
  sceneTargetPlatform: "short_video",
  reviewDecision: "keep",
  reviewDecisionNote: "Keep this direction for the next pass.",
  inspectorPrompt: "Product opening shot with a clean studio setup.",
  inspectorReferenceSummary: "Use the approved brief and main product reference summary.",
  inspectorStyleDirection: "Quiet premium commercial style.",
  inspectorRetryIntent: "If weak, revise composition before provider smoke.",
  assetProfileSeed: "examples/agentflow/production_memory_asset_profile_seed.example.json",
  promotionDecision: "promoted",
  promotionRationale: "Workbench deterministic flow; not durable memory.",
  feedbackNote: "Keep the reusable style/profile signal and prepare the next round.",
  health: null,
  capabilities: null,
  projects: [],
  workbench: null,
  activeView: "Create",
  selectedCardId: "",
  selectedVariantId: "",
  selectedArtifactId: "",
  artifact: null,
  lastResult: null,
  latestAssetTestJobId: "",
  loading: false,
  error: "",
};
